### PR TITLE
Metanorma-acme refactoring

### PR DESCRIPTION
**Pull request by w00lf**
metanorma/metanorma-vsd#4:

Refactoring to use metanorma-acme gem

@ronaldtse @opoudjis , refactored this gem to use metanorma-acme boilerplate. After the refactoring there are a slight changes in the output format:

Ascidoctor xml output changes:
Снимок экрана 2020-02-02 в 19 19 24

Снимок экрана 2020-02-02 в 19 19 54

Снимок экрана 2020-02-02 в 19 20 23

There is a difference in `docidentifier` tag between metnaroma-acme and old standrad, i see that 
before it used additional code value, how important is it?

2. Changes in html output:
Снимок экрана 2020-02-02 в 19 29 22
Снимок экрана 2020-02-02 в 19 29 11
Снимок экрана 2020-02-02 в 19 29 02

Again changes in `docidentifier` tag other changes are minor ones. @ronaldtse @opoudjis can you review these changes and tell if it ok.

### CODE REVIEW

**Comment by opoudjis** [comment]
The changes in html output are not meaningful: they are artifices of my introducing auto-formatting into XML for rspec so that the comparisons are smoother.

I think the custom identifier is significant, and if Ronald wants to retain it, we should make it the one retained identifier rather than dispense with it. @ronaldtse?

**Comment by ronaldtse** [comment]
Changes look fine to me, except that the document identifier should still show the document type and the document stage. i.e. "Ribose 1000" doesn't mean much.

@w00lf @opoudjis is there a way to define a "rendering scheme" for the identifier?

**Comment by opoudjis** [comment]
@ronaldtse Not at this time. Acme codes it as "Abbreviation" + docnumber.

We could (could) create a config parameter that is a Liquid template for document identifiers, drawing on metadata fields. I'm not in love with the idea, but I think it's the only way to keep RSD without any code, and it would end up becoming a separate ticket for me. 

For that scheme to work, we would need to add the config values into the hash of metadata values that go into liquid, and expand it. So the default identifier format would end up as `{{ org_abbrev}} {{ docnum }}`, and the current RSD identifier would be `{{ docnum }} {{ status_abbrev }}`.

@ronaldtse, do you want this, and is it worth the effort?

**Comment by ronaldtse** [comment]
> For that scheme to work, we would need to add the config values into the hash of metadata values that go into liquid, and expand it. So the default identifier format would end up as {{ org_abbrev}} {{ docnum }}, and the current RSD identifier would be {{ docnum }} {{ status_abbrev }}.

Agree. Where would that ticket go to then?

**Comment by opoudjis** [comment]
Acme. I'm creating it. https://github.com/metanorma/metanorma-acme/issues/18

@w00lf, don't let this ticket hold up RSD; we will repair RSD through this ticket. I think I will end up doing it.

**Comment by w00lf** [comment]
> Acme. I'm creating it. [metanorma/metanorma-acme#18](https://github.com/metanorma/metanorma-acme/issues/18)
> 
> @w00lf, don't let this ticket hold up RSD; we will repair RSD through this ticket. I think I will end up doing it.

Ok, so i am going to change specs fomat to the new one from metanorma-acme here and merge this PR?

**Comment by w00lf** [comment]
@opoudjis @ronaldtse , done with the specs, this PR can be merged

**Comment by w00lf** [comment]
UPDATE, i have found that part of the specs were skipped because of simplecov, that was because of wrong rng file provided. I have fixed this error, we got all specs, but now we have one failing spec from validation:

image

Thats rspec ./spec/asciidoctor/validate_spec.rb:19, i was not been able to found the place where this warning should be thrown, @ronaldtse , @opoudjis do you know where i can search for it in order to fix this spec?

**Comment by opoudjis** [comment]
I'll take care of this.

**Pull request merged**
