### PR TITLE
RSD restyling: https://github.com/metanorma/metanorma-rsd/issues/39

### PR DESCRIPTION
**Pull request by opoudjis**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@opoudjis is it possible to keep the publisher configurable?

**Comment by ronaldtse** [comment]
Screen Shot 2020-03-28 at 5 52 58 AM

Clause header is at font 11, but text at font 12. The smallest clause header should never be smaller than normal content.

**Comment by ronaldtse** [comment]
[SOURCE: ...] should be font 11 (same as NOTE/EXAMPLE size).

**Comment by opoudjis** [comment]
Your comments are being moved to a separate ticket. I will not action random comments not lodged in a proper channel.

**Comment by ronaldtse** [comment]
@opoudjis btw the changes here could be merged anytime, thanks.

**Pull request merged**
